### ISSUE TITLE
use alt attribute on image tags

### ISSUE THREAD

**Issue by rimmesbe** [CesBear/TeaCozy#1]
Try to get in the habit of describing your images with the alt attribute. This description will show up in case the image doesn't load, it is read by screen readers for accessibility, and it makes your code look more professional.
https://www.codecademy.com/articles/accessibility

https://github.com/CesBear/TeaCozy/blob/master/index.html#L34

**Comment by CesBear** [comment]
Thanks for pointing it out I always miss that, and I am sure next time will not happen , I updated alt attribute and pushed changes
