### ISSUE TITLE
html looks good

### ISSUE THREAD

**Issue by rimmesbe** [CesBear/TeaCozy#2]
Your html looks very good, well structured. I like that you are using some semantic tags `<header> <nav> <footer>` but there are many more. Take a look at this article for expanding what semantic tags you use: 
https://www.pluralsight.com/guides/html-css/semantic-html?aid=701j0000001heIqAAI&promo=&oid=&utm_source=google&utm_medium=ppc&utm_campaign=CA_Dynamic&utm_content=&utm_term=&gclid=CjwKCAjwlrnNBRBMEiwApKU4PBiUM7wtxiyqNw-6Zoikh6ChlNul6tTL839Zj2h_JNTZcK6PE5WWlRoCiOYQAvD_BwE

https://github.com/CesBear/TeaCozy/blob/master/index.html

**Comment by CesBear** [comment]
Thanks will check those and implement them!
