### ISSUE TITLE
SUMMARY

### ISSUE THREAD

**Issue by rimmesbe** [CesBear/TeaCozy#6]
Grade: Satisfactory

Summary: Nice job on this project, the site looks good. You used a lot of good techniques and structured your code well. Take a look at the issues I created as they will point out some best practice tweaks and some new techniques you can start incorporating. Overall well done, you are ready for the next units.

**Comment by CesBear** [comment]
I appreciate your comments, definitely I learned alot and will improve next projects with your comments!
Thanks!
