### ISSUE TITLE
Font is not consistent 

### ISSUE THREAD

**Issue by MDOR** [CesBear/TeaCozy#7]
# Issue 
The color and font type  is not consisten.
![image](https://user-images.githubusercontent.com/7268268/37012456-575ea3f0-20ba-11e8-997a-fe02b00c0efe.png)

Expected
![image](https://user-images.githubusercontent.com/7268268/37013077-94a30bea-20bd-11e8-96f1-b21b5f14f1b0.png)

**Comment by CesBear** [comment]
Thanks for pointing it out, will work on the fix

**Comment by CesBear** [comment]
### **Fixed.**  
I changed the menu font to be consistent with Logo font. Changes are pushed.

**Note:** The body content font will be updated in the enhancement suggested on Bug #8 .
