### ISSUE TITLE
First View is not cool

### ISSUE THREAD

**Issue by MDOR** [CesBear/TeaCozy#8]
# Issue 
We can take advantage of the selected colors and font type and tr to build something a bit styleshed according to the site.
![image](https://user-images.githubusercontent.com/7268268/37013129-f699aca0-20bd-11e8-964f-a9171dba347e.png)

**Comment by CesBear** [comment]
Thanks, It is awesome that how  a few changes convert a simple website into a web so elegant. Will try to reproduce it but help migth be needed.

**Comment by CesBear** [comment]
Fixed
